services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home-fonta
    restart: unless-stopped
    ports:
      - "8080:80"  # NGINX expos√© en local pour tests
    networks:
      - home-fonta-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  home-fonta-network:
    driver: bridge

